// Auto-generated by Style Dictionary. Do not edit.
package com.picke.app.ui.theme.tokens

import androidx.compose.ui.graphics.Color

object ComponentColorTokens {
    val bedgeFilledBackgroundDefault: Color = Color(0xFFEFEAE0)
    val bedgeFilledBackgroundInverse: Color = Color(0xFF893825)
    val bedgeFilledTextDefault: Color = Color(0xFF893825)
    val bedgeFilledTextInverse: Color = Color(0xFFFEFEFD)
    val bedgeOutlineText: Color = Color(0xFF893825)
    val bedgeOutlineBackround: Color = Color(0xFFFEFEFD)
    val bedgeOutlineBorder: Color = Color(0xFFE7D7D3)
    val inputBorderDefault: Color = Color(0xFFEFEAE0)
    val inputBorderActive: Color = Color(0xFFDAD1BF)
    val inputBorderError: Color = Color(0xFFC92D33)
    val inputSurfaceDefault: Color = Color(0xFFFEFEFD)
    val inputSurfaceDisabled: Color = Color(0xFFF9F7F2)
    val inputTextDefault: Color = Color(0xFF888786)
    val inputTextActive: Color = Color(0xFF393735)
    val inputTextError: Color = Color(0xFFC92D33)
    val buttonPrimaryBackgroundDefault: Color = Color(0xFF893825)
    val buttonPrimaryBackgroundPressed: Color = Color(0xFF653226)
    val buttonPrimaryBackgroundDisabled: Color = Color(0xFFD0AFA8)
    val buttonPrimaryTextDefault: Color = Color(0xFFFEFEFD)
    val buttonSecondaryBackgroundDefault: Color = Color(0xFFF9F7F2)
    val buttonSecondaryBackgroundPressed: Color = Color(0xFFF7F4EE)
    val buttonSecondaryBorderDefault: Color = Color(0xFFEFEAE0)
    val buttonSecondaryBorderPressed: Color = Color(0xFFE1B974)
    val buttonSecondaryTextDefault: Color = Color(0xFF2B2A28)
    val buttonSecondaryTextDisabled: Color = Color(0xFF888786)
}
