// Auto-generated by Style Dictionary. Do not edit.
package com.picke.app.ui.theme.tokens

import androidx.compose.ui.graphics.Color

object SemanticColorTokens {
    val textPrimary: Color = Color(0xFF131212)
    val textSecondary: Color = Color(0xFF222120)
    val textTertiary: Color = Color(0xFF393735)
    val textMuted: Color = Color(0xFF888786)
    val textInverse: Color = Color(0xFFFEFEFD)
    val textBrand: Color = Color(0xFF893825)
    val borderDefault: Color = Color(0xFFEFEAE0)
    val borderSubtle: Color = Color(0xFFDAD1BF)
    val borderDisabled: Color = Color(0xFFF5F1EA)
    val borderSelected: Color = Color(0xFFE1B974)
    val borderStrong: Color = Color(0xFF893825)
    val borderFocus: Color = Color(0xFFDAD1BF)
    val borderError: Color = Color(0xFFC92D33)
    val surfaceDefault: Color = Color(0xFFFEFEFD)
    val surfaceSubtle: Color = Color(0xFFF9F7F2)
    val surfaceTertiary: Color = Color(0xFFF7F4EE)
    val surfaceSelected: Color = Color(0xFF893825)
    val surfaceDisabled: Color = Color(0xFFD0AFA8)
    val backgroundDefault: Color = Color(0xFFFAFAF9)
    val backgroundSubtle: Color = Color(0xFFF5F5F4)
    val backgroundTertiary: Color = Color(0xFFEBEBEB)
    val backgroundBrand: Color = Color(0xFFFBF9F7)
    val backgroundInverse: Color = Color(0xFF1A1918)
    val backgroundOverlay: Color = Color(0xFF000000)
    val statusErrorError: Color = Color(0xFFC92D33)
    val statusErrorAlpha: Color = Color(0xFFC92D33)
    val statusWarningWarning: Color = Color(0xFFFFB400)
    val statusWarningAlpha: Color = Color(0xFFFFB400)
}
